### ISSUE TITLE
Error fetching new dataset

### ISSUE THREAD

**Issue by rodolfo-viana** [datasciencebr/serenata-toolbox#103]
I keep getting this error. Does anyone know what I am doing wrong?

![image](https://user-images.githubusercontent.com/25807981/27720735-b1482668-5d31-11e7-8738-d2eb234f3856.png)

**Comment by cuducos** [comment]
Does the directory `/tmp/serenata-data/` (used in your input lines 5 and 7) exists?

**Comment by rodolfo-viana** [comment]
I followed this instructions: https://github.com/datasciencebr/serenata-toolbox#example-3-generating-datasets

**Comment by cuducos** [comment]
Hum… got it where we got it wrong. What you called instructions are merely simple examples to show the package API — not a complete user guide. I'm sorry about that. Two possible (and non-exclusive) next steps here:

1. To fetch data either create this directory (`mkdir /tmp/serenata-data`) before running these snippets or replace `/tmp/serenata-data` in the code the your local directory in which you want the data to be downloaded to
1. Open a PR editing our text to let this clearer to other users ; )

Does that make sense?

**Comment by rodolfo-viana** [comment]
I did use `data/` and it worked. And `data/` is the folder we get when we run setup. So I guess the simplest correction is to edit the text, changing `/tmp/serenata-data` for `data/`.

I will do that. Thanx, man.
