### ISSUE TITLE
Missing sub quota from the final reimbursements dataset

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#106]
[We have a lot of sub quotas mapped](https://github.com/datasciencebr/serenata-toolbox/blob/master/serenata_toolbox/chamber_of_deputies/dataset.py#L103-L126)

But checking the latest reimbursements file generated on the terminal, and comparing it to the .csv file directly downloaded from the chamber of deputies @rodolfo-viana found that there is a whole subquota of reimbursements missing `(999, 'Flight ticket issue')`.

That accounts for over 20k of reimbursements.

**Comment by rodolfo-viana** [comment]
Over 20K of reimbursements and R$ 114M of `net_values`.
And I must correct something I told @jtemporal but I was mistaken: I got this not from the .csv file (which they do not update so often), but from .xml file.

**Comment by jtemporal** [comment]
Just to have this documented somewhere, we know that `.xml` files aren't easy to 'read' and it is pretty interesting the tool @rodolfo-viana used to deal with the `.xml` files: [Open Refine](http://openrefine.org). Maybe someone might need this in the future ;)

**Comment by jtemporal** [comment]
What is causing this isn't a bug yay 🎉 

What happens is, [there is a filter that cuts out receipts with `reimbursement_value` equals to 0](https://github.com/datasciencebr/serenata-toolbox/blob/master/serenata_toolbox/chamber_of_deputies/reimbursements.py#L64) because this means that, that document was not reimbursed.

**Comment by jtemporal** [comment]
Since this isn't a bug, I'm closing this =)
