### ISSUE TITLE
Deployment ideas

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#135]
With #134 almost good to merge, I would like to raise a question already raised [here](https://github.com/datasciencebr/serenata-toolbox/pull/131#issuecomment-324026373) and described bellow.

Today our deploys to PyPI are made whenever a PR is [merged into master](https://github.com/datasciencebr/serenata-toolbox/blob/d53d3f365d49dc2328ff83762be1328a932a1a0d/.travis.yml#L22). And that's pretty good!

Though there's a catch: PRs that **do not** have version bump break our build because PyPI don't accept file upload with a same version. Hence breaking our Travis Build.

There are a few approaches and I would like to get some thoughts on:

**1. create a release branch:**
  - Pros: We would only release those pull requests that really have code changes
  - Cons: A branch to update whenever we have meaningful changes which will generate double work to be done (update the branch, open a PR, merge it)

**2. everything is at least a patch bump:**
  - Pros: No build breaking, only on commit away from updating things
  - Cons: Rapidly increase in patch bumps (but considering that patches do not directly affect the way people use the toolbox that might not be such a big con)

**3. use the `condition` tag on deploy:**
  - Pros: Would put a condition to only deploy when setup had a bump
  - Cons: Don't know how to do this or if it is even possible to do so

**Comment by jtemporal** [comment]
I like a lot the idea 2. =)

**Comment by anaschwendler** [comment]
I'm tending to prefer the second idea, too :)

**Comment by cuducos** [comment]
I think we are good with the 2nd… closing by inactivity then  ; )
