### ISSUE TITLE
Could we use Pytest to help address the problems with total testing time for journey tests?

### ISSUE THREAD

**Issue by lipemorais** [datasciencebr/serenata-toolbox#140]
**What is the problem?**
[Journey tests takes too long to run](https://travis-ci.org/datasciencebr/serenata-toolbox/builds/270581133).
<img width="941" alt="screen shot 2017-08-31 at 19 08 24" src="https://user-images.githubusercontent.com/5021565/29947411-d2dc758e-8e7f-11e7-98bd-075a83fd38a0.png">

**How can this be addressed?**
I believe that the `--durations` of [Pytest](pytest.org) can help us understand what is going on, which test. Like in the image below:
<img width="1266" alt="screen shot 2017-08-31 at 19 10 34" src="https://user-images.githubusercontent.com/5021565/29947445-1f5bb366-8e80-11e7-8e45-8f841e47b8c3.png">

**Who could help with this issue?**
I could address it by myself but I'm open to have someone working on it with me. 

**Labels**
[question]

**Want to try it by yourself?**
`$ pip install pytest`
`pytest --verbose  --duration=10 tests/unit/` 

This command will run the tests under `tests/unit` folder show on a terminal report the 10th that takes more time to run.

**Comment by cuducos** [comment]
I'd love to see `pytest`around however I still think that the problem of `journey` is clearcut: we literally download more than 2MM reimbursements from the government serves. This is not what tests are for.

If we `mock` this downloads with useful subsets of real data ad fixtures, the waiting time is fixed IMHO.

**Comment by lipemorais** [comment]
@cuducos I completely agree with you. We need to start somewhere. I see this as very effective way to prioritize which tests attack first and will give us more return over our investment.

What do you think, @cuducos and @jtemporal ?

**Comment by cuducos** [comment]
Nothing _against_ `pytest`, feel free to go on ; )

**Comment by cuducos** [comment]
Closed by #142
