### ISSUE TITLE
Add PyPI label to README

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#148]
**What is the problem?**
We currently do not have our pipy version badge on the README, something like the image bellow:

<img width="105" alt="screen shot 2017-10-02 at 12 04 53 pm" src="https://user-images.githubusercontent.com/6595551/31084706-881e1462-a76b-11e7-98a5-8bd65de268c4.png">

**How can this be addressed?**
A pull request adding the pipy badge to README.md maybe using [Shields](https://shields.io)

**Who could help with this issue?**
@anaschwendler @cuducos @jtemporal

**Labels**
[hacktoberfest] [first-timers-only]

**Comment by marius92mc** [comment]
I will try this. 👍
