### ISSUE TITLE
Fix README.rst mal formatted lines

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-toolbox#161]
**What is the problem?**

Some code blocks are not formatted as expected:

<img width="981" alt="pasted_image_29_11_17_15_32" src="https://user-images.githubusercontent.com/4732915/33389612-a01b84e6-d51a-11e7-8a35-56da9e42e90c.png">

**How can this be addressed?**

Checking reStructuredText syntax.

**Who could help with this issue?**

Anyone interested I guess ; )

**Comment by Zubru22** [comment]
Hi there!
First-timer here, I cloned the repo, created branch for this issue, fixed those two block and I commited the changes. How do I push it to your repo? Sorry for noobie question but it's my first commit to a project which isn't mine :)

**Comment by anaschwendler** [comment]
Hi @Zubru22, welcome to our project!

There is totally no problem in asking, we are here to help!

You can read more about opening a PR (the way to push it to the repo) here: https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#the-basics

To open a PR to our project you must change it to a new branch:
```console
$ git checkout -b new-stuff
```

And push the content to the branch of your fork:
```console
$ git push origin new-stuff
```

And then you can open a [_Pull Request_](https://help.github.com/articles/creating-a-pull-request/) to our repo :)

**Comment by Zubru22** [comment]
@anaschwendler, I'm glad I could help even with something as trivial as fixing readme. Commiting to a project always seemed scary to me. I figured it out that I need to fork your project, push it to my fork and then create pull request. Already done it. Thanks :)

**Comment by anaschwendler** [comment]
Closed by #164
