### ISSUE TITLE
Failing to import "log"

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#173]
**What is the problem?**
Updated the serenata-de-amor environment with the toolbox `12.4.0` and got the following error:
<img width="986" alt="screen shot 2017-12-05 at 5 56 58 pm" src="https://user-images.githubusercontent.com/6595551/33727431-245f0120-db5f-11e7-81a9-f70ba0105433.png">

**How can this be addressed?**
Don't know

**Who could help with this issue?**
@anaschwendler 

**Labels**
[bug]

**Comment by anaschwendler** [comment]
It was my fault 😅

When merging #163 instead of bumping the version, I kept the same, so that didn't build up, fix in #174

**Comment by anaschwendler** [comment]
Closed by #175
