### ISSUE TITLE
Problem when fetching data from CEAP

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#24]
When running `ceap = serenata_toolbox.CEAPDataset('data/')`  I got this error `File is not a zip file`.

Same thing happened when running Rosie. I may be wrong but it is possible that is something wrong with the data.

Traceback when running Rosie with docker is [here](https://gist.github.com/jtemporal/7548458e7de0011ca2751a2b376501c3)

and the error while running the fetch with the toolbox with ipython is [here](https://gist.github.com/jtemporal/22b050c06939ccc6e9a0c0ab912e5c9d)

any thoughts?

**Comment by jonDel** [comment]
Did you try to check the zip file integrity outside python, like 
`7za t file.zip`
?

**Comment by jtemporal** [comment]
@jonDel I believe it was a problem with the chamber of deputies server or something like that. Today I was able to fetch the data without any problems.
since this is not a problem anymore I'm closing this issue.
