### ISSUE TITLE
Use logging module

### ISSUE THREAD

**Issue by jonDel** [datasciencebr/serenata-toolbox#25]
Use built-in logging module in order to get a structured and controllable way to output messages, instead of just using the function "print"

**Comment by vmesel** [comment]
This is a smart move @jonDel We would save some memory not printing things that are just necessary for a log.

**Comment by Ilozuluchris** [comment]
@jonDel @vmesel  Noob question:Can you give examples of messages that should be logged and not printed.

**Comment by cuducos** [comment]
Except when we're doing a kind of _progress bar_ (not sue if we do it here in the toolbox, but in general that would be a print with `end='\r'` kwarg) I believe logging would be better…

**Comment by jcemelanda** [comment]
As it wasn't assigned to anyone I implemented the changes in PR #156 .
