### ISSUE TITLE
Update package versioning

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#34]
Serenata Toolbox have 19 merged PR and most of them should generate a new package version if it were a released PYPI package. We should consider update the package version at least when there is new datasets being added or updated.

**Comment by jtemporal** [comment]
should see [Choosing a versioning scheme](https://packaging.python.org/distributing/#choosing-a-versioning-scheme) and [PEP440 on final releases](https://www.python.org/dev/peps/pep-0440/#final-releases).
I'm going to map later this week the version based on the changes each [merged PR](https://github.com/datasciencebr/serenata-toolbox/pulls?utf8=✓&q=is%3Apr%20is%3Aclosed%20is%3Amerged) using PEP440 as guide.

**Comment by jtemporal** [comment]
Following `major.minor.micro`. The proposed version updates follow this schema:
* all datasets additions were considered **minor** updates
* small changes (e.g. adding encoding) and small improvements that did not directly affect the toolbox workflow (e.g. better documentation) were considered **micro**
* bug fixes and new features (e.g. new methods and scripts) were all considered **major** changes

#33 minor: 7.4.1
#31 minor: 7.3.1
#28 minor: 7.2.1
#27 micro: 7.1.1
#26 minor: 7.1.0
#22 major: 7.0.0
#18 major: 6.0.0
#17 major: 5.0.0
#16 major: 4.0.0
#15 major: 3.0.0
#14 micro 2.3.1
#13 minor: 2.3.0
#12 minor: 2.2.0
#11 minor: 2.1.0
#10 major: 2.0.0
#6 major and micro: 1.0.1
#4 minor: 0.2.0
#3 minor: 0.1.0
#1 micro: 0.0.2

With all of the above in mind, the updated package version should be **7.4.1**

@cuducos do you have any concerns on the matter that you would like to add?

**Comment by cuducos** [comment]
Personally I like versioning convetions that focus on the public API, such as [Elm's one](https://github.com/elm-lang/elm-package#version-rules):

> * `PATCH` - the API is the same, no risk of breaking code
> * `MINOR` - values have been added, existing values are unchanged
> * `MAJOR` - existing values have been changed or removed

(What they call `PATCH` is what we call `micro`.)

What do you think about it?

**Comment by jtemporal** [comment]
@cuducos that seems about right! We can go with that from now on =)
