### ISSUE TITLE
Up-to-date reimbursements file

### ISSUE THREAD

**Issue by rodolfo-viana** [datasciencebr/serenata-toolbox#37]
Hey everyone.

I just ran `group_receipts.py` and got fresh new set of data (`2017-04-11-reimbusements.xz`).
Should I use it locally only or you guys believe it may be useful to upload to Amazon?

Love,

**Comment by rodolfo-viana** [comment]
Nah, forget it. I believe I did something wrong. 2017-04-11 is not working.

**Comment by cuducos** [comment]
Happens ; )

We tend to upload new stuff to Amazon since Rosie, the core of the project, always run with freshly downloaded data — aka updated. But if you plan to open a PR to the main repo with analysis made with this version of the dataset, then we'll need it on Amazon, ok?
