### ISSUE TITLE
Add timeout or similar to Downloader

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#42]
In case the download of one or more dataset is stuck we need to have a timeout or some other sort of breaking the wait gracefully.

**Comment by arioston** [comment]
Hi,

What you need is a simple timeout and an error message or need something more elaborate ?  

Remove ["timeout=None"](http://aiohttp.readthedocs.io/en/stable/client.html#timeouts) will make the connection use default timeout, this is one solution.

**Comment by cuducos** [comment]
I think the best approach wouldn't be to simply _remove_ [this `timeout=None`](https://github.com/datasciencebr/serenata-toolbox/blob/master/serenata_toolbox/datasets/downloader.py#L107). Instead I'd say that we user instantiate `Dataset` they could use a kwarg to customize it if they want. If they don't pass we assume it to be `None`. What do you think?

**Comment by cuducos** [comment]
Closed by #160
