### ISSUE TITLE
Missing version bump

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#50]
We missed a version bumps when merging #48 and #49 

Suggestions for version bump:

#48 - `micro` - typo fix, not much trouble there
#49 - `micro` - few renaming conventions based on the changes from CEAP to Chamber of Deputies

**Comment by cuducos** [comment]
Sorry, my bad. I'm not used to it **yet**. New PR bumping it twice sounds good? I'm gonna double check if changing the public API (renaming stuff) is a minor change though…

**Comment by jtemporal** [comment]
@cuducos that's my idea! check it and we can discuss it =)
>New PR bumping it twice sounds good?

Yes! o/

**Comment by cuducos** [comment]
>  @cuducos that's my idea! check it and we can discuss it =)

I think that if the public API changes, it's a major version bump (I expanded I in [the relevant topic](https://github.com/datasciencebr/serenata-toolbox/issues/34#issuecomment-299023973).

**Comment by jtemporal** [comment]
Closing this in favor of #51
