### ISSUE TITLE
Add the script to get the Federal Senate datasets.

### ISSUE THREAD

**Issue by anaschwendler** [datasciencebr/serenata-toolbox#52]
Ok guys, it's time.

Now that the toolbox is ready to receive a new dataset, I am working on a script to get the Federal Senate datasets.
They are pretty different from Chamber of Deputies, but we can work on it.

By now I will be fixing the final things to make Rosie works fine with this new toolbox, and then I will be working on bring the new script to the toolbox.

**Comment by cuducos** [comment]
Closed by #53
