### ISSUE TITLE
Missing version bump

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-toolbox#61]
@anaschwendler you forgot the version bump in #53 and I missed it while code reviewing. Can you fix that ASAP and open a new PR?

**Comment by anaschwendler** [comment]
Sure, doing it now!

**Comment by anaschwendler** [comment]
https://github.com/datasciencebr/serenata-toolbox/pull/62 that must solve it ;)

**Comment by cuducos** [comment]
Closed by #62
