### ISSUE TITLE
Better config Coveralls for accuracy

### ISSUE THREAD

**Issue by othman853** [datasciencebr/serenata-toolbox#75]
Hello, I hope it is not a problem to open an issue out of the blue like this. 

Lately, @lipemorais was showing me this project and, as a way to try to start contributing to it, I thought it would be interesting to replace Coveralls by another quality measuring tool. My reasons behind such suggestion are in the fact that the **Coveralls UI is very confusing**, I can't quickly get a picture of what is actually going on in the project when looking at its dashboard. Besides, **it is showing a quite imprecise metric** at this moment, since it's also considering third-party libraries in its analysis, lowering the metrics to only 25%. 

I believe that [CodeClimate](https://codeclimate.com) would be a better option to solve this problem. I've forked this project and configured its forked copy to be analyzed by CodeClimate. Below, it's possible to see a result of the first analysis:

<img width="1535" alt="screen shot 2017-05-24 at 12 57 19 am" src="https://cloud.githubusercontent.com/assets/4705127/26386310/4f9a0b2a-401c-11e7-9f98-c59501a35048.png">

Besides the code styling, it's also possible to harvest some metrics about testing coverage:

<img width="1679" alt="screen shot 2017-05-24 at 2 25 43 am" src="https://cloud.githubusercontent.com/assets/4705127/26388057/7fdf4dde-4028-11e7-8051-f0943252ede5.png">

<img width="1679" alt="screen shot 2017-05-24 at 2 25 59 am" src="https://cloud.githubusercontent.com/assets/4705127/26388098/b5028d96-4028-11e7-9d10-04fcd92dddbb.png">

I've also noticed that [Jarbas](https://github.com/datasciencebr/jarbas) makes use of both Coveralls and CodeClimate. Maybe, CodeClimate could be configured to be used as a test coverage reporter, replacing Coveralls there as well. 

I would like to apologize in advance if this is not the right way to open a new issue.

**Comment by cuducos** [comment]
Hi @othman853,

Many thanks for you suggestion. Unfortunately I tend to disagree.

>  Coveralls UI is very confusing

This is a quite subjective matter — I use it a lot so I feel familiar in their dashboard.

> it is showing a quite imprecise metric at this moment, since it's also considering third-party libraries

This is not a Coveralls problem, it's lack of configuration. We added it only [6 days ago](https://github.com/datasciencebr/serenata-toolbox/pull/64) and so we haven't fine tuned it yet. If we [configure it in a similar way](https://github.com/datasciencebr/jarbas/blob/master/.coveragerc) we did in Jarbas, [this doesn't happen](https://coveralls.io/github/datasciencebr/jarbas).

In spite of that Code Climate doesn't offer an analysis as complete as Landscape.io in terms of [style](https://landscape.io/github/datasciencebr/serenata-toolbox/143/messages/style), [code smell](https://landscape.io/github/datasciencebr/serenata-toolbox/143/messages/smell) and [errors](https://landscape.io/github/datasciencebr/serenata-toolbox/143/messages/error) — specially when using it with `veryhigh` strictness: it help us with docstrings (important for #23 as [I noted elsewhere](https://github.com/datasciencebr/serenata-toolbox/pull/72)), unused imports, thing accessed before creation, line breaks etc.

Anyway. I'm really glad you pointed is toward to some flaws in the configuration of our CI services, but I do not agree that changing would be better: after all the same settings needed now for Coveralls will also be needed with for Code Climate.

I'll let this issue open for debate for a while, but feel free to open an issue or PR fine tuning or Coveralls ; )

**Comment by othman853** [comment]
Hello! Thanks for the answer! I believe that a Coveralls tuning would end up being more appropriate then. I'll check how it can be fixed and open a PR. Sounds good?
Do you believe that a new issue should be open or we could open a PR to solve this current issue?

Once again, thank you very much! :)

**Comment by cuducos** [comment]
> I'll check how it can be fixed and open a PR. Sounds good?

That's awesome ; )

> Do you believe that a new issue should be open or we could open a PR to solve this current issue?

If you don't mind I can edit the title of this one — I think keeping the new issue togather with this discussion could be helpful. May I?

**Comment by othman853** [comment]
Absolutely! Thank you for all the help!
