### ISSUE TITLE
Create unittests

### ISSUE THREAD

**Issue by jonDel** [datasciencebr/serenata-toolbox#8]
Create unitary tests for this package. Sugestions:
- Use travis for online triggered testing at each commit;
- Use coverage and coveralls for test covering metrics.

**Comment by Irio** [comment]
Test suite and Travis CI configured in https://github.com/datasciencebr/serenata-toolbox/pull/14.

**Comment by cuducos** [comment]
Now that we have CI we could user coveralls.io to guide the writing of tests ; )

If it helps, Jarbas uses it.

**Comment by jonDel** [comment]
I can handle that.

**Comment by cuducos** [comment]
Closed in favor of #58 (as it discuss further details of tests enhancement and implementation)
