### ISSUE TITLE
Travis CI breaks the build after 10 minutes without any output no terminal

### ISSUE THREAD

**Issue by lipemorais** [datasciencebr/serenata-toolbox#92]
Looks that after some datasets were added to Toolbox the journey test of CEAP is not able to run on Travis CI because it takes more than 10 minutes without any log.
[Broken build](https://travis-ci.org/datasciencebr/serenata-toolbox/jobs/241772071)

**Comment by cuducos** [comment]
That's [Travis expected behavior](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) — but there's `travis_wait` if we really need it ; )

**Comment by lipemorais** [comment]
Thank you for explanation. 

Should we use  this feature, should we improve our tests to be faster or improve the UX/loggability?

**Comment by cuducos** [comment]
As I mentioned in #87 and #91: we need to improve our tests — the journey is not merely testing, it's literally running the app ; )
