### ISSUE TITLE
Failing tests don't make the suite/CI fail

### ISSUE THREAD

**Issue by Irio** [datasciencebr/serenata-toolbox#98]
Current status is a test suite failing with a green flag. When running locally, I get the same errors with a zero exit code.
https://travis-ci.org/datasciencebr/serenata-toolbox/jobs/242200049

**Comment by Irio** [comment]
At least few of the warnings shown are given to missing mocks. Adding them should remove message logs from the suite and let us see the real output.

**Comment by lipemorais** [comment]
Could share some of the logs here? I just can see a green build :/

**Comment by cuducos** [comment]
> Current status is a test suite failing with a green flag

What tells you the tests are failing? Can you be more specific?

Warning messages about `config.ini` are actually expected in [tests like those](https://github.com/datasciencebr/serenata-toolbox/blob/master/tests/unit/test_datasets_remote.py#L10-L24).

**Comment by cuducos** [comment]
> Could share some of the logs here? I just can see a green build :/

Logs are in Travis build @Irio posted.

Being green arguably is the bug if he's right about the expectation of red for this scenario — I just can't see why he expected this test to be red.

**Comment by lipemorais** [comment]
> Logs are in Travis build @Irio posted.

Yeah, I got it. I'm not sure which is the warning mentioned that should breaks the build.

After look at a comment here #68 I think that the warning is: `While fetching Seranata Toolbox not found file: /tmp/federal-senate-2007.csv ` inside the Travis CI log mentioned by @Irio.

**Comment by jtemporal** [comment]
since #105 was merged, I'm closing this one ;)
